theme: jekyll-theme-hacker
<form method="POST" action="https://formspree.io/YOUREMAILHERE">
  <input type="email" name="email" placeholder="Your email">
  <textarea name="message" placeholder="Your message"></textarea>
  <button type="submit">Send</button>
</form>
